# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://pipeline.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6a8ac8005a834754b80ecb40967bdfbf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_355d2a642b974f8ca5498ea9a81bc482 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: pipeline.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6a8ac8005a834754b80ecb40967bdfbf }}/password-generator:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pipeline'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_35a6c9ec280148029648399d8f0be4c1 }}
        images: 'pipeline.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6a8ac8005a834754b80ecb40967bdfbf }}/password-generator:${{ github.sha }}'